<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DFW10PF2" ignored="1" name="testSet" tests="5" failures="1" timestamp="03 Apr 2020 06:59:17 GMT" time="0.234" errors="0">
  <testcase name="testCase1" time="0.001" classname="com.fico.tests.TestClass1"/>
  <testcase name="testCase1" time="0.0" classname="com.fico.tests.TestClass1"/>
  <testcase name="testCase1" time="0.011" classname="com.fico.tests.TestClass1"/>
  <testcase name="testCase2" time="0.004" classname="com.fico.tests.TestClass1"/>
  <testcase name="testCase3" time="0.002" classname="com.fico.tests.TestClass2">
    <failure type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at com.fico.tests.TestClass2.testCase3(TestClass2.java:10)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testCase3 -->
  <testcase name="testCase4" time="0.0" classname="com.fico.tests.TestClass2">
    <ignored/>
  </testcase> <!-- testCase4 -->
</testsuite> <!-- testSet -->
